spring.application.name=connectauto

# --- Datasource (H2 em memoria) ---
spring.datasource.url=jdbc:h2:mem:connectauto
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# --- Hibernate / JPA ---
#(FAZ O MAPEAMENTO DAS ENTIDADES E SALVA NO BANCO DE DADOS)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# --- Console H2 ---
#(Permite acessar o console H2 pelo navegador)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
